[general]
version = 1

[[segment]]
name = "foo"

[[segment.mempool]]
size = 512
count = 10

[[segment]]
name = "bar"

[[segment.mempool]]
size = 512
count = 10

# The name of this segment defaults to the name of the group with write access
# The name of the group with write access defaults to the user launching the RouDi process
# Apologies if your username is either "foo" or "bar" - this will create a conflict.
[[segment]]

[[segment.mempool]]
size = 512
count = 10
